import type { Cafe, CrowdMatrix } from "@/app/types/cafe";

const baseCrowd = (
  overrides: Partial<CrowdMatrix> = {},
): CrowdMatrix => ({
  weekday0608: "normal",
  weekday0810: "normal",
  weekday1012: "normal",
  weekday1214: "normal",
  weekday1416: "normal",
  weekday1618: "normal",
  weekday1820: "crowded",
  weekday2022: "crowded",
  weekday2224: "crowded",
  weekend0608: "empty",
  weekend0810: "empty",
  weekend1012: "empty",
  weekend1214: "crowded",
  weekend1416: "crowded",
  weekend1618: "crowded",
  weekend1820: "crowded",
  weekend2022: "crowded",
  weekend2224: "crowded",
  ...overrides,
});

const joinAddress = (
  prefecture: string,
  line1: string,
  line2 = "",
  line3 = "",
) => [prefecture, line1, line2, line3].filter(Boolean).join("");

export const mockCafes: Cafe[] = [
  {
    id: "cafe-001",
    name: "Hakadoru Base Nihonbashi",
    facilityType: "cafe",
    area: "中央区",
    prefecture: "東京都",
    postalCode: "103-0027",
    addressLine1: "中央区日本橋1-1-1",
    addressLine2: "ハカドルビル5F",
    addressLine3: "",
    address: joinAddress("東京都", "中央区日本橋1-1-1", "ハカドルビル5F"),
    access: "日本橋駅A5出口から徒歩3分。再開発エリアの大通り沿い。",
    nearestStation: "日本橋駅",
    phone: "03-1234-5678",
    status: "open",
    timeLimit: "2時間制",
    hoursWeekdayFrom: "08:00",
    hoursWeekdayTo: "21:00",
    hoursWeekendFrom: "09:00",
    hoursWeekendTo: "20:00",
    hoursNote: "祝日は10:00~19:00で営業。",
    regularHolidays: ["火曜日"],
    seats: 48,
    wifi: true,
    outlet: "most",
    lighting: "bright",
    meetingRoom: false,
    hasPrivateBooths: false,
    smoking: "no_smoking",
    alcohol: "night_only",
    mainMenu: "ブレンドコーヒー、カフェラテ、季節のタルト",
    services: ["テラス席あり", "窓際席あり", "充電器貸出あり"],
    paymentMethods: ["現金", "クレカ", "交通系IC"],
    recommendedWorkStyles: ["PC作業", "オンライン会議"],
    crowdMatrix: baseCrowd({
      weekday0608: "empty",
      weekday0810: "empty",
      weekday1012: "empty",
      weekday1214: "normal",
      weekday1416: "normal",
      weekday1618: "normal",
    }),
    ambienceCasual: 3,
    ambienceModern: 4,
    ambassadorComment:
      "朝は静かで集中しやすい。\n電源席が多く、オンライン会議にも向いています。",
    website: "https://example.com/nihonbashi",
    instagramUrl: "",
    tiktokUrl: "",
    firstRequestAccountId: null,
    instagramPostUrl1: "",
    instagramPostUrl2: "",
    instagramPostUrl3: "",
    smokingNote: "",
    equipmentNote: "窓際の電源席は混雑時でも利用しやすい。",
    latitude: 35.682,
    longitude: 139.772,
    imageMainPath: "cafes/cafe-001/main.jpg",
    imageExteriorPath: "cafes/cafe-001/exterior.jpg",
    imageInteriorPath: "cafes/cafe-001/interior.jpg",
    imagePowerPath: "cafes/cafe-001/power.jpg",
    imageDrinkPath: "cafes/cafe-001/drink.jpg",
    imageFoodPath: "cafes/cafe-001/food.jpg",
    imageOtherPaths: [],
    imageCaptions: {
      main: "店内全景",
      exterior: "ビル外観",
      interior: "窓際席",
      power: "電源席",
      drink: "ハンドドリップ",
      food: "季節のタルト",
    },

    approval_status: "approved",
    deleted_at: null,
    updated_at: "2025-01-05T09:00:00+09:00",
  },
  {
    id: "cafe-002",
    name: "Focus Lounge Shibuya",
    facilityType: "coworking",
    area: "渋谷区",
    prefecture: "東京都",
    postalCode: "150-0002",
    addressLine1: "渋谷区渋谷2-10-12",
    addressLine2: "クロスタワー12F",
    addressLine3: "",
    address: joinAddress("東京都", "渋谷区渋谷2-10-12", "クロスタワー12F"),
    access:
      "渋谷駅東口徒歩6分。青山通り沿い、クロスタワーの12階受付にて入館。",
    nearestStation: "渋谷駅",
    phone: "03-9876-5432",
    status: "recently_opened",
    timeLimit: "制限なし",
    hoursWeekdayFrom: "00:00",
    hoursWeekdayTo: "23:59",
    hoursWeekendFrom: "07:00",
    hoursWeekendTo: "23:00",
    hoursNote: "日曜はメンテナンスのため23:00クローズ。",
    regularHolidays: [],
    seats: 60,
    wifi: true,
    outlet: "all",
    lighting: "normal",
    meetingRoom: true,
    hasPrivateBooths: true,
    smoking: "no_smoking",
    alcohol: "available",
    mainMenu: "ハンドドリップ、サンドイッチ、日替わりスープ",
    services: ["個室ブース", "24h営業", "モニター貸出あり", "ブランケット貸出あり"],
    paymentMethods: ["クレカ", "QR決済"],
    recommendedWorkStyles: ["深夜作業", "ブレスト"],
    crowdMatrix: baseCrowd({
      weekday1820: "normal",
      weekday2022: "normal",
      weekend0608: "normal",
      weekend0810: "normal",
      weekend1012: "normal",
    }),
    ambienceCasual: 2,
    ambienceModern: 5,
    ambassadorComment: "夜間の静けさが抜群。24h営業でナイトワーカー向き。",
    website: "https://example.com/shibuya",
    instagramUrl: "",
    tiktokUrl: "",
    firstRequestAccountId: null,
    instagramPostUrl1: "",
    instagramPostUrl2: "",
    instagramPostUrl3: "",
    smokingNote: "",
    equipmentNote: "会議室はアプリ予約制で、1回最大90分まで。",
    latitude: 35.659,
    longitude: 139.703,
    imageMainPath: "cafes/cafe-002/main.jpg",
    imageExteriorPath: "cafes/cafe-002/exterior.jpg",
    imageInteriorPath: "cafes/cafe-002/interior.jpg",
    imagePowerPath: "cafes/cafe-002/power.jpg",
    imageDrinkPath: "cafes/cafe-002/drink.jpg",
    imageFoodPath: "cafes/cafe-002/food.jpg",
    imageOtherPaths: [],
    imageCaptions: {
      main: "コワーキングエリア",
      exterior: "エントランス",
      interior: "集中ブース",
      power: "個別コンセント",
      drink: "バリスタメニュー",
      food: "軽食カウンター",
    },

    approval_status: "approved",
    deleted_at: null,
    updated_at: "2025-01-05T09:00:00+09:00",
  },
  {
    id: "cafe-003",
    name: "Quiet Corner Ogikubo",
    facilityType: "cafe",
    area: "杉並区",
    prefecture: "東京都",
    postalCode: "167-0051",
    addressLine1: "杉並区荻窪4-20-7",
    addressLine2: "",
    addressLine3: "カームプレイス1F",
    address: joinAddress("東京都", "杉並区荻窪4-20-7", "", "カームプレイス1F"),
    access:
      "荻窪駅南口徒歩4分。商店街を抜けた住宅地の角に位置します。店舗前に駐輪スペースあり。",
    nearestStation: "荻窪駅",
    phone: "03-1133-2468",
    status: "closed",
    timeLimit: "90分",
    hoursWeekdayFrom: "10:00",
    hoursWeekdayTo: "19:00",
    hoursWeekendFrom: "10:00",
    hoursWeekendTo: "18:00",
    hoursNote: "季節イベント時は営業時間が変動する場合があります。",
    regularHolidays: ["水曜日"],
    seats: 32,
    wifi: false,
    outlet: "some",
    lighting: "dark",
    meetingRoom: false,
    hasPrivateBooths: false,
    smoking: "allowed",
    alcohol: "unavailable",
    mainMenu: "深煎りコーヒー、チーズケーキ",
    services: ["テイクアウト"],
    paymentMethods: ["現金"],
    recommendedWorkStyles: ["読書", "集中作業"],
    crowdMatrix: baseCrowd({
      weekday0608: "normal",
      weekday0810: "normal",
      weekday1012: "normal",
      weekday1214: "empty",
      weekday1416: "empty",
      weekday1618: "empty",
      weekend1820: "normal",
      weekend2022: "normal",
    }),
    ambienceCasual: 4,
    ambienceModern: 2,
    ambassadorComment:
      "照明が抑えめで夜におすすめ。\n静かさを重視したい人向け。",
    website: "https://example.com/ogikubo",
    instagramUrl: "",
    tiktokUrl: "",
    firstRequestAccountId: null,
    instagramPostUrl1: "",
    instagramPostUrl2: "",
    instagramPostUrl3: "",
    smokingNote: "",
    equipmentNote: "電源席は壁際の一部のみ。延長コードの貸出あり。",
    latitude: 35.704,
    longitude: 139.621,
    imageMainPath: "cafes/cafe-003/main.jpg",
    imageExteriorPath: "cafes/cafe-003/exterior.jpg",
    imageInteriorPath: "cafes/cafe-003/interior.jpg",
    imagePowerPath: "cafes/cafe-003/power.jpg",
    imageDrinkPath: "cafes/cafe-003/drink.jpg",
    imageFoodPath: undefined,
    imageOtherPaths: [],
    imageCaptions: {
      main: "静かな店内",
      exterior: "店舗外観",
      interior: "地下スペース",
      power: "壁際コンセント",
      drink: "ハンドドリップ",
    },

    approval_status: "pending",
    deleted_at: "2025-01-02T09:00:00+09:00",
    updated_at: "2025-01-02T09:00:00+09:00",
  },
];
