import type { Cafe, CrowdMatrix } from "@/app/types/cafe";

const baseCrowd = (
  overrides: Partial<CrowdMatrix> = {},
): CrowdMatrix => ({
  weekdayMorning: "normal",
  weekdayAfternoon: "normal",
  weekdayEvening: "crowded",
  weekendMorning: "empty",
  weekendAfternoon: "crowded",
  weekendEvening: "crowded",
  ...overrides,
});

const joinAddress = (
  prefecture: string,
  line1: string,
  line2 = "",
  line3 = "",
) => [prefecture, line1, line2, line3].filter(Boolean).join("");

export const mockCafes: Cafe[] = [
  {
    id: "cafe-001",
    name: "Hakadoru Base Nihonbashi",
    facilityType: "cafe",
    area: "中央区",
    prefecture: "東京都",
    postalCode: "103-0027",
    addressLine1: "中央区日本橋1-1-1",
    addressLine2: "ハカドルビル5F",
    addressLine3: "",
    address: joinAddress("東京都", "中央区日本橋1-1-1", "ハカドルビル5F"),
    access: "日本橋駅A5出口から徒歩3分。再開発エリアの大通り沿い。",
    phone: "03-1234-5678",
    status: "open",
    timeLimit: "2時間制",
    hoursWeekdayFrom: "08:00",
    hoursWeekdayTo: "21:00",
    hoursWeekendFrom: "09:00",
    hoursWeekendTo: "20:00",
    hoursNote: "祝日は10:00~19:00で営業。",
    regularHolidays: ["火曜日"],
    seats: 48,
    wifi: true,
    outlet: "most",
    lighting: "bright",
    meetingRoom: false,
    allowsShortLeave: false,
    hasPrivateBooths: false,
    parking: false,
    smoking: "no_smoking",
    coffeePrice: 680,
    bringOwnFood: "allowed",
    alcohol: "night_only",
    services: ["テラス席あり", "窓際席あり", "充電器貸出あり"],
    paymentMethods: ["現金", "クレカ", "交通系IC"],
    customerTypes: ["ビジネス", "学生"],
    recommendedWorkStyles: ["PC作業", "オンライン会議"],
    crowdMatrix: baseCrowd({
      weekdayMorning: "empty",
      weekdayAfternoon: "normal",
    }),
    ambienceCasual: 3,
    ambienceModern: 4,
    ambassadorComment:
      "朝は静かで集中しやすい。\n電源席が多く、オンライン会議にも向いています。",
    website: "https://example.com/nihonbashi",
    latitude: 35.682,
    longitude: 139.772,
    imageMainPath: "cafes/cafe-001/main.jpg",
    imageExteriorPath: "cafes/cafe-001/exterior.jpg",
    imageInteriorPath: "cafes/cafe-001/interior.jpg",
    imagePowerPath: "cafes/cafe-001/power.jpg",
    imageDrinkPath: "cafes/cafe-001/drink.jpg",
    imageFoodPath: "cafes/cafe-001/food.jpg",
    imageOtherPaths: [],
    imageCaptions: {
      main: "店内全景",
      exterior: "ビル外観",
      interior: "窓際席",
      power: "電源席",
      drink: "ハンドドリップ",
      food: "季節のタルト",
    },
    deleted_at: null,
    updated_at: "2025-01-05T09:00:00+09:00",
  },
  {
    id: "cafe-002",
    name: "Focus Lounge Shibuya",
    facilityType: "coworking",
    area: "渋谷区",
    prefecture: "東京都",
    postalCode: "150-0002",
    addressLine1: "渋谷区渋谷2-10-12",
    addressLine2: "クロスタワー12F",
    addressLine3: "",
    address: joinAddress("東京都", "渋谷区渋谷2-10-12", "クロスタワー12F"),
    access:
      "渋谷駅東口徒歩6分。青山通り沿い、クロスタワーの12階受付にて入館。",
    phone: "03-9876-5432",
    status: "recently_opened",
    timeLimit: "制限なし",
    hoursWeekdayFrom: "00:00",
    hoursWeekdayTo: "23:59",
    hoursWeekendFrom: "07:00",
    hoursWeekendTo: "23:00",
    hoursNote: "日曜はメンテナンスのため23:00クローズ。",
    regularHolidays: [],
    seats: 60,
    wifi: true,
    outlet: "all",
    lighting: "normal",
    meetingRoom: true,
    allowsShortLeave: true,
    hasPrivateBooths: true,
    parking: false,
    smoking: "no_smoking",
    coffeePrice: 720,
    bringOwnFood: "drinks_only",
    alcohol: "available",
    services: ["個室ブース", "24h営業", "モニター貸出あり", "ブランケット貸出あり"],
    paymentMethods: ["クレカ", "QR決済"],
    customerTypes: ["ビジネス", "フリーランス"],
    recommendedWorkStyles: ["深夜作業", "ブレスト"],
    crowdMatrix: baseCrowd({
      weekdayEvening: "normal",
      weekendMorning: "normal",
    }),
    ambienceCasual: 2,
    ambienceModern: 5,
    ambassadorComment: "夜間の静けさが抜群。24h営業でナイトワーカー向き。",
    website: "https://example.com/shibuya",
    latitude: 35.659,
    longitude: 139.703,
    imageMainPath: "cafes/cafe-002/main.jpg",
    imageExteriorPath: "cafes/cafe-002/exterior.jpg",
    imageInteriorPath: "cafes/cafe-002/interior.jpg",
    imagePowerPath: "cafes/cafe-002/power.jpg",
    imageDrinkPath: "cafes/cafe-002/drink.jpg",
    imageFoodPath: "cafes/cafe-002/food.jpg",
    imageOtherPaths: [],
    imageCaptions: {
      main: "コワーキングエリア",
      exterior: "エントランス",
      interior: "集中ブース",
      power: "個別コンセント",
      drink: "バリスタメニュー",
      food: "軽食カウンター",
    },
    deleted_at: null,
    updated_at: "2025-01-05T09:00:00+09:00",
  },
  {
    id: "cafe-003",
    name: "Quiet Corner Ogikubo",
    facilityType: "cafe",
    area: "杉並区",
    prefecture: "東京都",
    postalCode: "167-0051",
    addressLine1: "杉並区荻窪4-20-7",
    addressLine2: "",
    addressLine3: "カームプレイス1F",
    address: joinAddress("東京都", "杉並区荻窪4-20-7", "", "カームプレイス1F"),
    access:
      "荻窪駅南口徒歩4分。商店街を抜けた住宅地の角に位置します。店舗前に駐輪スペースあり。",
    phone: "03-1133-2468",
    status: "closed",
    timeLimit: "90分",
    hoursWeekdayFrom: "10:00",
    hoursWeekdayTo: "19:00",
    hoursWeekendFrom: "10:00",
    hoursWeekendTo: "18:00",
    hoursNote: "季節イベント時は営業時間が変動する場合があります。",
    regularHolidays: ["水曜日"],
    seats: 32,
    wifi: false,
    outlet: "some",
    lighting: "dark",
    meetingRoom: false,
    allowsShortLeave: false,
    hasPrivateBooths: false,
    parking: false,
    smoking: "separated",
    coffeePrice: 600,
    bringOwnFood: "not_allowed",
    alcohol: "unavailable",
    services: ["テイクアウト"],
    paymentMethods: ["現金"],
    customerTypes: ["地元"],
    recommendedWorkStyles: ["読書", "集中作業"],
    crowdMatrix: baseCrowd({
      weekdayMorning: "normal",
      weekdayAfternoon: "empty",
      weekendEvening: "normal",
    }),
    ambienceCasual: 4,
    ambienceModern: 2,
    ambassadorComment:
      "照明が抑えめで夜におすすめ。\n静かさを重視したい人向け。",
    website: "https://example.com/ogikubo",
    latitude: 35.704,
    longitude: 139.621,
    imageMainPath: "cafes/cafe-003/main.jpg",
    imageExteriorPath: "cafes/cafe-003/exterior.jpg",
    imageInteriorPath: "cafes/cafe-003/interior.jpg",
    imagePowerPath: "cafes/cafe-003/power.jpg",
    imageDrinkPath: "cafes/cafe-003/drink.jpg",
    imageFoodPath: undefined,
    imageOtherPaths: [],
    imageCaptions: {
      main: "静かな店内",
      exterior: "店舗外観",
      interior: "地下スペース",
      power: "壁際コンセント",
      drink: "ハンドドリップ",
    },
    deleted_at: "2025-01-02T09:00:00+09:00",
    updated_at: "2025-01-02T09:00:00+09:00",
  },
];
