import type { Cafe } from "@/app/types/cafe";

export const mockCafes: Cafe[] = [
  {
    id: "cafe-001",
    name: "Hakadoru Base Nihonbashi",
    area: "日本橋",
    address: "東京都中央区日本橋1-1-1",
    phone: "03-1234-5678",
    access: "日本橋駅A5出口から徒歩3分",
    status: "open",
    seats: 48,
    seatType: "木製テーブル / ソファ",
    wifi: true,
    wifiSpeed: "下り80Mbps / 上り45Mbps",
    outlet: "most",
    lighting: "bright",
    meetingRoom: false,
    parking: false,
    smoking: "no_smoking",
    coffeePrice: 680,
    bringOwnFood: "allowed",
    alcohol: "night_only",
    services: ["テラス席あり", "おかわり割引", "窓際席あり"],
    paymentMethods: ["現金", "クレカ", "交通系IC"],
    crowdedness: "normal",
    customerTypes: ["ビジネス", "学生"],
    ambienceCasual: 3,
    ambienceModern: 4,
    ambassadorComment: "朝は静かで集中しやすい。電源席が多い。",
    website: "https://example.com/nihonbashi",
    timeLimit: "2時間",
    hoursWeekday: "8:00-21:00",
    hoursWeekend: "9:00-20:00",
    imagePath: "cafes/cafe-001/cover.jpg",
    latitude: 35.683893,
    longitude: 139.774811,
    deleted_at: null,
    updated_at: "2025-01-01T12:00:00+09:00",
  },
  {
    id: "cafe-002",
    name: "Focus Lounge Shibuya",
    area: "渋谷",
    address: "東京都渋谷区渋谷2-10-12",
    phone: "03-9876-5432",
    access: "渋谷駅東口 徒歩6分",
    status: "recently_opened",
    seats: 60,
    seatType: "ソファ / カウンター",
    wifi: true,
    wifiSpeed: "下り120Mbps / 上り90Mbps",
    outlet: "all",
    lighting: "normal",
    meetingRoom: true,
    parking: false,
    smoking: "no_smoking",
    coffeePrice: 720,
    bringOwnFood: "drinks_only",
    alcohol: "available",
    services: ["個室ブース", "24h営業", "モニター貸出あり"],
    paymentMethods: ["クレカ", "QR決済"],
    crowdedness: "crowded",
    customerTypes: ["ビジネス", "フリーランス"],
    ambienceCasual: 2,
    ambienceModern: 5,
    ambassadorComment: "ナイトタイムの静けさが抜群。",
    website: "https://example.com/shibuya",
    timeLimit: "制限なし",
    hoursWeekday: "24h",
    hoursWeekend: "24h",
    imagePath: "cafes/cafe-002/cover.jpg",
    latitude: 35.6595,
    longitude: 139.7023,
    deleted_at: null,
    updated_at: "2025-01-04T10:30:00+09:00",
  },
  {
    id: "cafe-003",
    name: "Quiet Corner Ogikubo",
    area: "荻窪",
    address: "東京都杉並区荻窪4-20-7",
    phone: "03-1133-2468",
    access: "荻窪駅南口 徒歩4分",
    status: "closed",
    seats: 32,
    seatType: "木製 / カウンター",
    wifi: false,
    wifiSpeed: "",
    outlet: "some",
    lighting: "dark",
    meetingRoom: false,
    parking: false,
    smoking: "separated",
    coffeePrice: 600,
    bringOwnFood: "not_allowed",
    alcohol: "unavailable",
    services: ["テイクアウト"],
    paymentMethods: ["現金"],
    crowdedness: "empty",
    customerTypes: ["地元"],
    ambienceCasual: 4,
    ambienceModern: 2,
    ambassadorComment: "照明が落ち着いていて夜におすすめ。",
    website: "https://example.com/ogikubo",
    timeLimit: "90分",
    hoursWeekday: "10:00-19:00",
    hoursWeekend: "10:00-18:00",
    imagePath: "cafes/cafe-003/cover.jpg",
    latitude: 35.7042,
    longitude: 139.6194,
    deleted_at: "2025-01-02T09:00:00+09:00",
    updated_at: "2025-01-02T09:00:00+09:00",
  },
];
