-- ハカドルカフェ テストデータ (カフェ情報のみ)
-- 作成日: 2025-11-07
-- バージョン: 2.1

INSERT INTO cafes (
  id, name, facility_type, area,
  prefecture, postal_code, address_line1, address_line2, address_line3, address,
  access,
  hours_weekday_from, hours_weekday_to,
  hours_weekend_from, hours_weekend_to,
  hours_note, regular_holidays,
  time_limit, status, website, phone,
  seats, wifi, outlet, lighting,
  meeting_room, allow_short_leave, private_booths, parking, smoking,
  coffee_price, bring_own_food, alcohol,
  services, payment_methods, customer_types, recommended_work,
  crowd_levels,
  ambience_casual, ambience_modern, ambassador_comment,
  image_main_path, image_exterior_path, image_interior_path, image_power_path, image_drink_path, image_food_path, image_other_paths,
  deleted_at, created_at, updated_at
) VALUES
(
  'cafe0000-0000-0000-0000-000000000001',
  'Hakadoru Base Nihonbashi',
  'cafe',
  '中央区',
  '東京都',
  '103-0027',
  '中央区日本橋室町1-5-5',
  'COREDO室町3 1F',
  '',
  '東京都中央区日本橋室町1-5-5 COREDO室町3 1F',
  '日本橋駅A5出口 徒歩3分',
  '08:00', '21:00',
  '09:00', '20:00',
  '祝日は10:00～19:00で営業。',
  '["火曜日"]',
  '2時間制',
  'open',
  'https://bluebottlecoffee.jp/',
  '03-6225-0000',
  45,
  TRUE,
  'most',
  'bright',
  FALSE, FALSE, FALSE, FALSE,
  'no_smoking',
  680,
  'allowed',
  'night_only',
  '["テイクアウト", "窓際席あり", "デカフェあり", "充電器貸出あり"]',
  '["現金", "クレカ", "交通系IC"]',
  '["ビジネス", "観光客", "地元"]',
  '["PC作業", "読書"]',
  '{"weekdayMorning":"normal","weekdayAfternoon":"normal","weekdayEvening":"normal","weekendMorning":"normal","weekendAfternoon":"normal","weekendEvening":"normal"}',
  3,
  4,
  '静かで天井が高く集中できる。午前中がおすすめ。',
  '/images/cafe/pexels-chevanon-302896.jpg',
  '/images/cafe/exterior-default.jpg',
  '/images/cafe/pexels-chevanon-312418.jpg',
  '/images/cafe/power-default.jpg',
  '/images/cafe/drink-default.jpg',
  '/images/cafe/food-default.jpg',
  '[]',
  NULL,
  NOW(), NOW()
),
(
  'cafe0000-0000-0000-0000-000000000002',
  'Focus Lounge Shibuya',
  'coworking',
  '渋谷区',
  '東京都',
  '150-0002',
  '渋谷区渋谷2-10-12',
  'クロスタワー12F',
  '',
  '東京都渋谷区渋谷2-10-12 クロスタワー12F',
  '渋谷駅東口 徒歩6分',
  '00:00', '23:59',
  '07:00', '23:00',
  '日曜は23:00クローズ。',
  '[]',
  '制限なし',
  'open',
  'https://streamercoffee.com/',
  '03-6427-3705',
  60,
  TRUE,
  'all',
  'normal',
  TRUE, TRUE, TRUE, FALSE,
  'no_smoking',
  720,
  'drinks_only',
  'available',
  '["個室ブース", "24h営業", "モニター貸出あり", "ブランケット貸出あり"]',
  '["クレカ", "QR決済"]',
  '["ビジネス", "フリーランス"]',
  '["PC作業", "打合せ"]',
  '{"weekdayMorning":"normal","weekdayAfternoon":"normal","weekdayEvening":"normal","weekendMorning":"normal","weekendAfternoon":"crowded","weekendEvening":"crowded"}',
  2,
  5,
  '夜間の静けさが抜群。ナイトワーカー向き。',
  '/images/cafe/pexels-enginakyurt-2299028.jpg',
  '/images/cafe/exterior-default.jpg',
  '/images/cafe/pexels-enginakyurt-2347380.jpg',
  '/images/cafe/power-default.jpg',
  '/images/cafe/drink-default.jpg',
  '/images/cafe/food-default.jpg',
  '[]',
  NULL,
  NOW(), NOW()
),
(
  'cafe0000-0000-0000-0000-000000000003',
  'Quiet Corner Ogikubo',
  'cafe',
  '杉並区',
  '東京都',
  '167-0051',
  '杉並区荻窪4-20-7',
  '',
  'カームプレイス1F',
  '東京都杉並区荻窪4-20-7 カームプレイス1F',
  '荻窪駅南口 徒歩4分',
  '10:00', '19:00',
  '10:00', '18:00',
  'イベント時は営業時間変動あり。',
  '["水曜日"]',
  '90分',
  'closed',
  'https://example.com/ogikubo',
  '03-1133-2468',
  32,
  FALSE,
  'some',
  'dark',
  FALSE, FALSE, FALSE, FALSE,
  'separated',
  600,
  'not_allowed',
  'unavailable',
  '["テイクアウト"]',
  '["現金"]',
  '["地元"]',
  '["読書", "勉強"]',
  '{"weekdayMorning":"normal","weekdayAfternoon":"empty","weekdayEvening":"normal","weekendMorning":"empty","weekendAfternoon":"normal","weekendEvening":"normal"}',
  4,
  2,
  '照明が抑えめで夜におすすめ。',
  '/images/cafe/pexels-fotios-photos-1402407.jpg',
  '/images/cafe/exterior-default.jpg',
  '/images/cafe/pexels-fotios-photos-1833769.jpg',
  '/images/cafe/power-default.jpg',
  '/images/cafe/drink-default.jpg',
  NULL,
  '[]',
  NULL,
  NOW(), NOW()
),
(
  'cafe0000-0000-0000-0000-000000000004',
  'スターバックス コーヒー 新宿マルイ本館店',
  'cafe',
  '新宿区',
  '東京都',
  '160-0022',
  '新宿区新宿3-30-13',
  '新宿マルイ本館1F',
  '',
  '東京都新宿区新宿3-30-13 新宿マルイ本館1F',
  '新宿三丁目駅B2出口 徒歩1分',
  '08:00', '21:00',
  '08:00', '21:00',
  '',
  '[]',
  '制限なし',
  'open',
  'https://example.com/starbucks-shinjuku',
  '03-0000-0000',
  80,
  TRUE,
  'most',
  'normal',
  FALSE, FALSE, FALSE, FALSE,
  'no_smoking',
  480,
  'allowed',
  'unavailable',
  '["テイクアウト", "窓際席あり"]',
  '["現金", "クレカ", "QR決済", "交通系IC"]',
  '["ビジネス", "学生", "観光客", "地元"]',
  '["PC作業", "勉強"]',
  '{"weekdayMorning":"crowded","weekdayAfternoon":"crowded","weekdayEvening":"crowded","weekendMorning":"crowded","weekendAfternoon":"crowded","weekendEvening":"crowded"}',
  3,
  3,
  '駅近で便利だが混雑しがち。電源は一部のみ。',
  '/images/cafe/default-main.jpg',
  '/images/cafe/exterior-default.jpg',
  '/images/cafe/default-interior.jpg',
  '/images/cafe/power-default.jpg',
  '/images/cafe/drink-default.jpg',
  '/images/cafe/food-default.jpg',
  '[]',
  NULL,
  NOW(), NOW()
),
(
  'cafe0000-0000-0000-0000-000000000005',
  'WIRED CAFE 六本木',
  'hybrid',
  '港区',
  '東京都',
  '106-0032',
  '港区六本木6-10-1',
  '六本木ヒルズ けやき坂通り',
  '',
  '東京都港区六本木6-10-1 六本木ヒルズ けやき坂通り',
  '六本木駅1C出口 徒歩3分',
  '08:00', '23:00',
  '08:00', '23:00',
  '',
  '[]',
  '制限なし',
  'open',
  'https://example.com/wired',
  '03-0000-0000',
  70,
  TRUE,
  'most',
  'normal',
  FALSE, FALSE, FALSE, TRUE,
  'separated',
  620,
  'allowed',
  'available',
  '["テラス席あり", "窓際席あり", "駐車場", "24h営業"]',
  '["現金", "クレカ", "QR決済", "交通系IC"]',
  '["ビジネス", "観光客"]',
  '["PC作業", "打合せ"]',
  '{"weekdayMorning":"normal","weekdayAfternoon":"normal","weekdayEvening":"normal","weekendMorning":"normal","weekendAfternoon":"normal","weekendEvening":"normal"}',
  3,
  4,
  '夜遅くまで営業していて便利。アルコールも楽しめる。',
  '/images/cafe/default-main.jpg',
  '/images/cafe/exterior-default.jpg',
  '/images/cafe/default-interior.jpg',
  '/images/cafe/power-default.jpg',
  '/images/cafe/drink-default.jpg',
  '/images/cafe/food-default.jpg',
  '[]',
  NULL,
  NOW(), NOW()
),
(
  'cafe0000-0000-0000-0000-000000000006',
  '猿田彦珈琲 恵比寿本店',
  'cafe',
  '渋谷区',
  '東京都',
  '150-0013',
  '渋谷区恵比寿1-6-6',
  '',
  '',
  '東京都渋谷区恵比寿1-6-6',
  '恵比寿駅東口 徒歩5分',
  '08:00', '20:00',
  '09:00', '20:00',
  '',
  '[]',
  '2時間制',
  'open',
  'https://sarutahiko.co/',
  '03-5422-0000',
  25,
  FALSE,
  'none',
  'normal',
  FALSE, FALSE, FALSE, FALSE,
  'no_smoking',
  550,
  'not_allowed',
  'unavailable',
  '["テイクアウト"]',
  '["現金", "クレカ", "QR決済", "交通系IC"]',
  '["地元", "観光客"]',
  '["読書"]',
  '{"weekdayMorning":"normal","weekdayAfternoon":"normal","weekdayEvening":"normal","weekendMorning":"normal","weekendAfternoon":"normal","weekendEvening":"normal"}',
  4,
  3,
  'コーヒーは絶品だがWi-Fiと電源なし。長時間作業には不向き。',
  '/images/cafe/default-main.jpg',
  '/images/cafe/exterior-default.jpg',
  '/images/cafe/default-interior.jpg',
  '/images/cafe/power-default.jpg',
  '/images/cafe/drink-default.jpg',
  '/images/cafe/food-default.jpg',
  '[]',
  NULL,
  NOW(), NOW()
),
(
  'cafe0000-0000-0000-0000-000000000007',
  'Cafe MUJI 有楽町',
  'cafe',
  '千代田区',
  '東京都',
  '100-0005',
  '千代田区丸の内3-8-3',
  '無印良品 有楽町 2F',
  '',
  '東京都千代田区丸の内3-8-3 無印良品 有楽町 2F',
  '有楽町駅中央口 徒歩3分',
  '10:00', '21:00',
  '10:00', '21:00',
  '',
  '[]',
  '制限なし',
  'open',
  'https://cafe.muji.com/',
  '03-5208-0000',
  50,
  TRUE,
  'half',
  'bright',
  FALSE, FALSE, FALSE, FALSE,
  'no_smoking',
  400,
  'allowed',
  'unavailable',
  '["テイクアウト", "窓際席あり"]',
  '["現金", "クレカ", "QR決済", "交通系IC"]',
  '["ビジネス", "ファミリー", "地元"]',
  '["勉強", "読書"]',
  '{"weekdayMorning":"normal","weekdayAfternoon":"normal","weekdayEvening":"normal","weekendMorning":"normal","weekendAfternoon":"normal","weekendEvening":"normal"}',
  3,
  4,
  'シンプルで落ち着いた雰囲気。長居しやすい。',
  '/images/cafe/default-main.jpg',
  '/images/cafe/exterior-default.jpg',
  '/images/cafe/default-interior.jpg',
  '/images/cafe/power-default.jpg',
  '/images/cafe/drink-default.jpg',
  '/images/cafe/food-default.jpg',
  '[]',
  NULL,
  NOW(), NOW()
),
(
  'cafe0000-0000-0000-0000-000000000008',
  'TRUNK(HOTEL) KUSHI TART STAND & COFFEE',
  'other',
  '目黒区',
  '東京都',
  '153-0042',
  '目黒区青葉台1-14-1',
  '',
  '',
  '東京都目黒区青葉台1-14-1',
  '中目黒駅 徒歩7分',
  '08:00', '20:00',
  '08:00', '20:00',
  '',
  '[]',
  '制限なし',
  'open',
  'https://trunk-hotel.com/',
  '03-5784-0000',
  35,
  TRUE,
  'most',
  'bright',
  FALSE, FALSE, FALSE, FALSE,
  'no_smoking',
  750,
  'allowed',
  'night_only',
  '["テラス席あり", "窓際席あり", "デカフェあり"]',
  '["現金", "クレカ", "QR決済", "交通系IC"]',
  '["ビジネス", "観光客"]',
  '["PC作業"]',
  '{"weekdayMorning":"empty","weekdayAfternoon":"normal","weekdayEvening":"normal","weekendMorning":"empty","weekendAfternoon":"normal","weekendEvening":"normal"}',
  2,
  5,
  'おしゃれで静かな穴場カフェ。Wi-Fi速度も速い。',
  '/images/cafe/default-main.jpg',
  '/images/cafe/exterior-default.jpg',
  '/images/cafe/default-interior.jpg',
  '/images/cafe/power-default.jpg',
  '/images/cafe/drink-default.jpg',
  '/images/cafe/food-default.jpg',
  '[]',
  NULL,
  NOW(), NOW()
);
